# Generated by Django 2.2.1 on 2019-05-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190528_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstances',
            new_name='BookInstance',
        ),
    ]
